openapi: 3.0.0
info:
  title: AjaxAmp
  version: '1.0'
  description: The REST API for the Winamp plugin AjaxAMP
  contact:
    name: Michael Veroukis
    email: mveroukis@blitterhead.com
servers:
  - url: 'http://localhost:5151'
paths:
  /console.xml:
    get:
      summary: console.xml
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/console'
      operationId: get-console.xml
      description: Get the state of the player
  /playlist.xml:
    get:
      summary: playlist.xml
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Playlist'
              examples: {}
      operationId: get-playlist.xml
      description: Get the current playlist
      parameters:
        - schema:
            type: string
          in: query
          name: id
  /play:
    post:
      summary: play
      tags: []
      responses:
        '200':
          description: OK
      operationId: post-play
      description: Play
  /pause:
    post:
      summary: pause
      tags: []
      responses:
        '200':
          description: OK
      operationId: post-pause
      description: Pause
  /stop:
    post:
      summary: stop
      tags: []
      responses:
        '200':
          description: OK
      operationId: post-stop
      description: Stop playback
  /prev:
    post:
      summary: prev
      tags: []
      responses:
        '200':
          description: OK
      operationId: post-prev
      description: Play previous track
  /next:
    post:
      summary: next
      tags: []
      responses:
        '200':
          description: OK
      operationId: post-next
      description: Plays next track
  /rew5s:
    post:
      summary: rew5s
      tags: []
      responses:
        '200':
          description: OK
      operationId: post-rew5s
      description: rewinds 5 seconds
  /ffw5s:
    post:
      summary: ffw5s
      tags: []
      responses:
        '200':
          description: OK
      operationId: post-ffw5s
      description: Fastforward 5 seconds
  /togglerepeat:
    post:
      summary: togglerepeat
      tags: []
      responses:
        '200':
          description: OK
      operationId: post-togglerepeat
      description: Toggles repeat of playlist
  /toggleshuffle:
    post:
      summary: toggleshuffle
      tags: []
      responses:
        '200':
          description: OK
      operationId: post-toggleshuffle
      description: Toggles shuffle of playlist
  '/setvolume/{level}':
    post:
      summary: setvolume
      tags: []
      responses:
        '200':
          description: OK
      operationId: post-setvolume
      description: 'Set volume. Level is from 0 to 255, where 255 is max volume.'
    parameters:
      - schema:
          type: integer
          maximum: 255
          minimum: 0
        name: level
        in: path
        required: true
  '/setposition/{pos}':
    post:
      summary: setposition
      tags: []
      responses:
        '200':
          description: OK
      operationId: post-setposition
      description: 'Set position, where pos is a float from 0 to 1.'
    parameters:
      - schema:
          type: number
          default: 0
          maximum: 1
          minimum: 0
        name: pos
        in: path
        required: true
  /library.js:
    get:
      summary: Library
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/library_folder'
      operationId: get-library.js
      description: Get files list from a specific path.
      parameters:
        - schema:
            type: string
          in: query
          name: path
          description: 'The remte path to a folder that contains music files. To perform a search, the path should start with "search://". To search only folder names, use "searchf://".'
          required: true
        - schema:
            type: integer
          in: query
          name: sort
        - schema:
            type: string
          in: query
          name: sortdir
    parameters: []
  /setplaylistpos:
    post:
      summary: setplaylistpos
      tags: []
      responses:
        '200':
          description: OK
      operationId: post-setplaylistpos
      parameters:
        - schema:
            type: integer
          in: query
          name: index
      description: Starts playback at the specified position
  /clearPlaylist:
    post:
      summary: clearPlaylist
      tags: []
      responses:
        '200':
          description: OK
      operationId: post-clearPlaylist
      description: Removes all tracks from the playlist but does not affect playback of current track
  /playfile:
    post:
      summary: Playfile
      tags: []
      responses:
        '200':
          description: OK
      operationId: post-playfile
      parameters:
        - schema:
            type: string
          in: query
          name: filename
        - schema:
            type: string
          in: query
          name: title
      description: Replaces the playlist with the specified file/folder and begins playback
  /enqueuefile:
    post:
      summary: enqueuefile
      tags: []
      responses:
        '200':
          description: OK
      operationId: post-enqueuefile
      parameters:
        - schema:
            type: string
          in: query
          name: filename
        - schema:
            type: string
          in: query
          name: title
      description: Enqueues a file at the end of the playlist
  /enqueueFileNext:
    post:
      summary: enqueueFileNext
      tags: []
      responses:
        '200':
          description: OK
      operationId: post-enqueueFileNext
      parameters:
        - schema:
            type: string
          in: query
          name: filename
        - schema:
            type: string
          in: query
          name: title
      description: Enqueues a file immediately after the currently playing file in the playlist
  /deleteplaylistitem:
    post:
      summary: deleteplaylistitem
      tags: []
      responses:
        '200':
          description: OK
      operationId: post-deleteplaylistitem
      parameters:
        - schema:
            type: integer
          in: query
          name: index
      description: Removes an item from the playlist at the specified index
  /moveplaylistitem:
    post:
      summary: moveplaylistitem
      tags: []
      responses:
        '200':
          description: OK
      operationId: post-moveplaylistitem
      parameters:
        - schema:
            type: integer
          in: query
          name: from
        - schema:
            type: integer
          in: query
          name: to
      description: Moves a playlist item from one position to another
components:
  schemas:
    console:
      title: console
      type: object
      x-tags:
        - Player
      description: ''
      properties:
        artist:
          type: string
          example: U2
        album:
          type: string
          example: Achtung Baby
        title:
          type: string
          example: Mysterious Ways
        filename:
          type: string
          example: "C:\\Music\\Mysterious Ways.mp3"
        volume:
          type: integer
          format: int32
          example: 255
          minimum: 0
          maximum: 255
        isRepeat:
          type: boolean
        isShuffle:
          type: boolean
        length:
          type: string
        bitrate:
          type: integer
        position:
          type: number
        lengthms:
          type: integer
    playlist_track:
      title: playlist_track
      type: object
      properties:
        index:
          type: integer
        title:
          type: string
        filename:
          type: string
          format: uri
    Playlist:
      title: playlist
      type: object
      description: ''
      properties:
        playing:
          type: integer
        dirty:
          type: integer
          default: 0
          format: int32
          example: 1
          minimum: 0
          maximum: 1
        entries:
          type: array
          items:
            $ref: '#/components/schemas/playlist_track'
      required:
        - playing
        - dirty
        - entries
    library_file:
      title: library_file
      type: object
      properties:
        name:
          type: string
        path:
          type: string
        type:
          type: string
        '':
          type: string
    library_folder:
      title: library_folder
      type: object
      properties:
        path:
          type: string
        auth:
          type: string
        files:
          type: array
          items:
            $ref: '#/components/schemas/library_file'
